# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - stock

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
    ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Current IP Address
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Add IP address to SQL Server
        run: az sql server firewall-rule create --resource-group blog --server stockappdbserver --name ghactions --start-ip-address ${{ steps.ip.outputs.ipv4 }} --end-ip-address ${{ steps.ip.outputs.ipv4 }}

      - name: Install EF Tools
        run: dotnet tool install --global dotnet-ef

      - name: Build with dotnet
        run: dotnet build ./StockApp.sln --configuration Release

      - name: Update Database
        run: dotnet ef database update --project ./StockApp.Api/StockApp.Api.csproj

      - name: dotnet publish
        run: dotnet publish ./StockApp.sln -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FA072768506D4046BAE954B40A51118B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E38DEDFC063B4AAF8258ACCF79498942 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F22B4D8F6B5F4573A401146179170B05 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'stock'
          slot-name: 'Production'
          package: .
          
